services:

  duplicati:
    image: duplicati/duplicati:2.0.7.100_canary_2023-12-27
    container_name: duplicati
    environment:
      - TZ=Etc/UTC
    volumes:
      - /docker_data/duplicati/data:/data
      - /docker_data:/docker_data
      - /docker_backups:/docker_backups
    ports:
      - 8200:8200
    restart: unless-stopped

networks:
  duplicati:
    name: duplicati
    external: true
